### PR TITLE
Added abstract in pod as suggested by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @sdondley 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by sdondley** [comment]
Thanks. I'm not sure what the proper way to integrate this in with dist::zilla is, though. I'll research it.

**Comment by manwar** [comment]
What you had was the correct way to add abstract using dzil except when using [Podweaver] you should not have NAME section defined explicitly in the pod. Instead you just need to add the abstract as comment at the top "# ABSTRACT: you abstract here"

**Comment by sdondley** [comment]
OK, good to know. Thanks a lot.

**Comment by sdondley** [comment]
Your pull request leaves in the =head1 NAME section. Is that correct?

**Comment by manwar** [comment]
I think I tried without =head1 NAME and it didn't work, so I guess it does need to be defined.

**Comment by sdondley** [comment]
Odd, when I do dzil build now the SYNOPSIS section is blank.

**Comment by sdondley** [comment]
I had to delete the =head1 NAME section to get the synopsis back. Maybe we have different version of podweaver? Dunno.

**Comment by manwar** [comment]
This is strange. I will have a look.

**Comment by manwar** [comment]
You are right. =head1 NAME is not required in the pod.

**Comment by sdondley** [comment]
OK, thanks for the commit. Should get me a kwalitee ranking of 100 now.

**Pull request merged**
